<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
<<<<<<<< HEAD:DatabaseService/Logic/DatabaseService.Logic.csproj
    <ProjectReference Include="..\Dal\DatabaseService.Dal.csproj" />
========
    <ProjectReference Include="..\..\Core\Core.csproj" />
>>>>>>>> message-queue:GatewayServiceApi/DatabaseConnectionLib.csproj
  </ItemGroup>

</Project>
