services:
  gatewayserviceapi:
    image: ${DOCKER_REGISTRY-}gatewayserviceapi
    build:
      context: .
      dockerfile: GatewayServiceApi/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      emailnotificationapi:
        condition: service_started
      messangernotificationapi:
        condition: service_started
      pushnotificationapi:
        condition: service_started
      smsnotificationapi:
        condition: service_started
      databaseservice.api:
        condition: service_started


  emailnotificationapi:
    image: ${DOCKER_REGISTRY-}emailnotificationapi
    build:
      context: .
      dockerfile: Notification/EmailNotificationApi/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy


  messangernotificationapi:
    image: ${DOCKER_REGISTRY-}messangernotificationapi
    build:
      context: .
      dockerfile: Notification/MessangerNotificationApi/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy


  pushnotificationapi:
    image: ${DOCKER_REGISTRY-}pushnotificationapi
    build:
      context: .
      dockerfile: Notification/PushNotificationApi/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy


  smsnotificationapi:
    image: ${DOCKER_REGISTRY-}smsnotificationapi
    build:
      context: .
      dockerfile: Notification/SMSNotificationApi/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy


  databaseservice.api:
    image: ${DOCKER_REGISTRY-}databaseserviceapi
    build:
      context: .
      dockerfile: DatabaseService/Api/Dockerfile
    depends_on:
        postgres:
            condition: service_healthy


  postgres:
    image: postgres:17.0
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: NotificationBase
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d NotificationBase" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # порт для приложений
      - "15672:15672"   # UI RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5


  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 10s
      retries: 5


  grafana:
    image: grafana/grafana:12.3.1
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5


  logstash:
    image: docker.elastic.co/logstash/logstash:9.2.3
    container_name: logstash
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 30s
      timeout: 10s
      retries: 5


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health | grep -E '\"status\":\"(green|yellow)\"'"]
      interval: 30s
      timeout: 10s
      retries: 5


  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  prometheus_data:
  grafana_data:
  es_data:

